---
vms:

  # NOTE: All `box:` declarations in this example point to vagrantcloud.com
  # and require Vagrant 1.5.0 or newer to function.

  - name: pe-381-master
    debug-kit: true
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - r10k
      - el-utils
      - pe-forward-console
      - el-stop-firewall
      - el-fix-path
      - 2gb-memory
      - base

  - name: pe-381-agent
    debug-kit: true
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - el-stop-firewall
      - el-fix-path
      - base

  - name: pe-381-agent-jenkins
    debug-kit: true
    box: puppetlabs/centos-6.6-64-nocm
    roles:
      - forward-jenkins
      - el-stop-firewall
      - el-fix-path
      - 2gb-memory
      - base

  - name: pe-381-agent-app
    debug-kit: true
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - el-stop-firewall
      - el-fix-path
      - base

# vim: set ft=yaml:
